---
dontChroot: false
timeout: 180
verbose: true
script:
  - "id ergenos >/dev/null 2>&1 && userdel -r ergenos || true"
  - "rm -rf /home/ergenos"
  - "rm -f /etc/gdm/custom.conf"
  - "rm -rf /etc/systemd/system/gdm.service.d"
  - "rm -rf /etc/systemd/system/getty@tty1.service.d"
  - "rm -f /etc/sudoers.d/ergenos-live"
  - "rm -f /usr/lib/sysusers.d/ergenos-live.conf"
  - "rm -f /usr/lib/tmpfiles.d/ergenos-live.conf"
  - "rm -f /etc/mkinitcpio.conf.d/archiso.conf"
  - "rm -f /etc/mkinitcpio.d/linux.preset"
  - "rm -f /boot/initramfs-linux.img /boot/vmlinuz-linux"
  - "rm -f /etc/ssh/sshd_config.d/10-archiso.conf"
  - "rm -f /etc/udev/rules.d/98-ergenos-cdrom-loop.rules"
  - "rm -f /etc/systemd/resolved.conf.d/archiso.conf"
  - "rm -f /etc/systemd/logind.conf.d/do-not-suspend.conf"
  - "rm -f /etc/systemd/journald.conf.d/volatile-storage.conf"
  - "rm -f /etc/systemd/system-generators/systemd-gpt-auto-generator"
  - "rm -f /etc/systemd/system/etc-pacman.d-gnupg.mount"
  - "rm -rf /etc/pacman.d/gnupg"
  - "install -d -m 0755 /etc/pacman.d/gnupg"
  - "pacman-key --init"
  - "pacman-key --populate archlinux"
  - "rm -f /etc/systemd/network/20-ethernet.network"
  - "rm -f /etc/systemd/network/20-wlan.network"
  - "rm -f /etc/systemd/network/20-wwan.network"
  - "rm -rf /etc/systemd/system/systemd-networkd-wait-online.service.d"
  - "rm -f /etc/systemd/system/sysinit.target.wants/systemd-time-wait-sync.service"
  - "cp /usr/lib/modules/*-zen/vmlinuz /boot/vmlinuz-linux-zen"
  - "rm -f /etc/motd"
  - "rm -f /etc/issue"
  - "/usr/local/lib/ergenos/enable-multilib"
  - "rm -f /etc/systemd/system/multi-user.target.wants/pacman-init.service"
  - "rm -f /etc/systemd/system/multi-user.target.wants/choose-mirror.service"
  - "rm -f /etc/systemd/system/multi-user.target.wants/sshd.service"
  - "rm -f /etc/systemd/system/multi-user.target.wants/livecd-talk.service"
  - "rm -f /etc/systemd/system/sound.target.wants/livecd-alsa-unmuter.service"
  - "rm -rf /etc/systemd/system/cloud-init.target.wants"
  - "rm -f /etc/systemd/system/choose-mirror.service"
  - "rm -f /etc/systemd/system/livecd-talk.service"
  - "rm -f /etc/systemd/system/livecd-alsa-unmuter.service"
  - "rm -f /etc/systemd/system/pacman-init.service"
  - "rm -f /root/.automated_script.sh"
  - "rm -f /root/.zlogin"
  - "rm -f /usr/local/bin/choose-mirror"
  - "rm -f /usr/local/bin/Installation_guide"
  - "rm -f /usr/local/bin/livecd-sound"
  - "rm -rf /usr/local/share/livecd-sound"
