---
dontChroot: false
timeout: 30
verbose: true
script:
  - "rm -f /etc/gdm/custom.conf"
  - "rm -f /etc/sudoers.d/ergenos-live"
  - "rm -f /usr/lib/sysusers.d/ergenos-live.conf"
  - "rm -f /usr/lib/tmpfiles.d/ergenos-live.conf"
  - "rm -f /etc/mkinitcpio.conf.d/archiso.conf"
  - "cp /usr/lib/modules/*-zen/vmlinuz /boot/vmlinuz-linux-zen"
  - "rm -f /etc/motd"
  - "rm -f /etc/issue"
  - 'sed -i "/^#\[multilib\]/{s/^#//;n;s/^#//}" /etc/pacman.conf'
  - "rm -f /etc/systemd/system/multi-user.target.wants/pacman-init.service"
  - "rm -f /etc/systemd/system/multi-user.target.wants/choose-mirror.service"
  - "rm -f /etc/systemd/system/multi-user.target.wants/sshd.service"
  - "rm -f /etc/systemd/system/multi-user.target.wants/livecd-talk.service"
  - "rm -f /etc/systemd/system/sound.target.wants/livecd-alsa-unmuter.service"
  - "rm -f /root/.automated_script.sh"
  - "rm -f /usr/local/bin/choose-mirror"
