---
dontChroot: false
timeout: 1800

packagechooser_software_sources:
  official: "/usr/local/lib/ergenos/configure-software-source official"
  yay: "/usr/local/lib/ergenos/configure-software-source yay"
  paru: "/usr/local/lib/ergenos/configure-software-source paru"
  chaotic: "/usr/local/lib/ergenos/configure-software-source chaotic"
  "*": "/usr/bin/false"

