---
dontChroot: false
timeout: 60
verbose: true
script:
  - "/usr/local/lib/ergenos/enable-multilib"
  - "rm -f /usr/local/lib/ergenos/enable-multilib"
  - "/usr/local/lib/ergenos/configure-resume"
  - "rm -f /usr/local/lib/ergenos/configure-resume"
  - "if test -x /usr/local/lib/ergenos/backup-boot; then /usr/local/lib/ergenos/backup-boot; fi"
  - "if test -f /etc/snapper/configs/root; then snapper --no-dbus -c root create --description 'ErgenOS initial installation' --cleanup-algorithm number; fi"
