---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true
  - name: "gdm.service"
    action: "enable"
    mandatory: true
  - name: "ergenos-flathub-setup.service"
    action: "enable"
    mandatory: true
  - name: "graphical.target"
    action: "set-default"
    mandatory: true
  - name: "systemd-networkd.service"
    action: "disable"
  - name: "iwd.service"
    action: "disable"
  - name: "pacman-init.service"
    action: "mask"
