---
modules-search: [ local ]

instances:
  - id: cleanup
    module: shellprocess
    config: cleanup.conf
  - id: finalize
    module: shellprocess
    config: finalize.conf
  - id: setup-snapper
    module: shellprocess
    config: setup-snapper.conf
  - id: software_sources
    module: packagechooser
    config: packagechooser-software-sources.conf
  - id: software_sources
    module: contextualprocess
    config: contextualprocess-software-sources.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - packagechooser@software_sources
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - shellprocess@cleanup
      - machineid
      - locale
      - keyboard
      - localecfg
      - fstab
      - initcpiocfg
      - shellprocess@setup-snapper
      - initcpio
      - users
      - contextualprocess@software_sources
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - shellprocess@finalize
      - bootloader
      - umount
  - show:
      - finished

branding: ergenos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
